### ISSUE TITLE
Memory leaks in tf2_ros

### ISSUE THREAD

**Issue by zhoulaifu** [ros2/geometry2#376]
Running test_buffer_client (of the tf2_ros package) with the Address Sanitizer (https://en.wikipedia.org/wiki/AddressSanitizer) detected memory leaks in the package. Below is the error message. 

Tested on ros:eloquent. 

```
root@cdefda6a27aa:/opt/ros_ws# ./build/tf2_ros/test_buffer_client
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from TestBufferClient
[ RUN      ] TestBufferClient.lookup_transform_available
[       OK ] TestBufferClient.lookup_transform_available (201 ms)
[ RUN      ] TestBufferClient.lookup_transform_unavailable
[       OK ] TestBufferClient.lookup_transform_unavailable (301 ms)
[ RUN      ] TestBufferClient.can_transform_available
[       OK ] TestBufferClient.can_transform_available (160 ms)
[ RUN      ] TestBufferClient.can_transform_unavailable
[WARN] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[       OK ] TestBufferClient.can_transform_unavailable (209 ms)
[----------] 4 tests from TestBufferClient (871 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (885 ms total)
[  PASSED  ] 4 tests.

=================================================================
==37==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0x7f3da0c1a448 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0448)
    #1 0x55ddce607693 in rclcpp_action::Client<tf2_msgs::action::LookupTransform>::SharedPtr rclcpp_action::create_client<tf2_msgs::action::LookupTransform>(std::shared_ptr<rclcpp::node_interfaces::NodeBaseInterface>, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>, std::shared_ptr<rclcpp::node_interfaces::NodeLoggingInterface>, std::shared_ptr<rclcpp::node_interfaces::NodeWaitablesInterface>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<rclcpp::callback_group::CallbackGroup>) (/opt/ros_ws/build/tf2_ros/test_buffer_client+0x1dc693)
    #2 0x55ddce6004f4 in rclcpp_action::Client<tf2_msgs::action::LookupTransform>::SharedPtr rclcpp_action::create_client<tf2_msgs::action::LookupTransform, std::shared_ptr<rclcpp::Node> >(std::shared_ptr<rclcpp::Node>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<rclcpp::callback_group::CallbackGroup>) (/opt/ros_ws/build/tf2_ros/test_buffer_client+0x1d54f4)
    #3 0x55ddce5f7823 in tf2_ros::BufferClient::BufferClient<std::shared_ptr<rclcpp::Node> >(std::shared_ptr<rclcpp::Node>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double const&, std::chrono::duration<long, std::ratio<1l, 1000000000l> > const&) (/opt/ros_ws/build/tf2_ros/test_buffer_client+0x1cc823)
    #4 0x55ddce5ea969 in std::_MakeUniq<tf2_ros::BufferClient>::__single_object std::make_unique<tf2_ros::BufferClient, std::shared_ptr<rclcpp::Node>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::shared_ptr<rclcpp::Node>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/opt/ros_ws/build/tf2_ros/test_buffer_client+0x1bf969)
    #5 0x55ddce5dc1bc in TestBufferClient::SetUp() (/opt/ros_ws/build/tf2_ros/test_buffer_client+0x1b11bc)
    #6 0x55ddce747304 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/ros/eloquent/src/gtest_vendor/./src/gtest.cc:2447
    #7 0x55ddce727b90 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/ros/eloquent/src/gtest_vendor/./src/gtest.cc:2483
    #8 0x55ddce67c152 in testing::Test::Run() /opt/ros/eloquent/src/gtest_vendor/./src/gtest.cc:2517
    #9 0x55ddce67f26e in testing::TestInfo::Run() /opt/ros/eloquent/src/gtest_vendor/./src/gtest.cc:2703
    #10 0x55ddce680fbd in testing::TestCase::Run() /opt/ros/eloquent/src/gtest_vendor/./src/gtest.cc:2825
    #11 0x55ddce6b8c9d in testing::internal::UnitTestImpl::RunAllTests() /opt/ros/eloquent/src/gtest_vendor/./src/gtest.cc:5216
    #12 0x55ddce74ccec in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/ros/eloquent/src/gtest_vendor/./src/gtest.cc:2447
    #13 0x55ddce72c8b7 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/ros/eloquent/src/gtest_vendor/./src/gtest.cc:2483
    #14 0x55ddce6b1b07 in testing::UnitTest::Run() /opt/ros/eloquent/src/gtest_vendor/./src/gtest.cc:4824
    #15 0x55ddce5d4ba4 in RUN_ALL_TESTS() (/opt/ros_ws/build/tf2_ros/test_buffer_client+0x1a9ba4)
    #16 0x55ddce5d00da in main /opt/ros_ws/src/geometry2/tf2_ros/test/test_buffer_client.cpp:192
    #17 0x7f3d9ee0dbf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

```

**Comment by zhoulaifu** [comment]
The error seems to be in rclcpp. Also I should have used foxy instead.
