### ISSUE TITLE
rclpy BufferClient lookup_transform not working, timeout

### ISSUE THREAD

**Issue by charlielito** [ros2/geometry2#438]
## Bug report

**Required Info:**

- Operating System:
  - Docker + Ubuntu 20.04
- Installation type:
  - From binaries
- Version or commit hash:
  - Foxy
- DDS implementation:
  - Fast-RTPS,
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
Calling `BufferClient.lookup_transform` always timeouts although if I call the buffer server via ros2 cli it works. 

Create a node like the following:

```python
#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from tf2_ros.buffer_client import BufferClient
from rclpy.duration import Duration
from std_msgs.msg import Empty

class TestNode(Node):
    def __init__(
        self,
    ):
        super().__init__("test_node")
        self.cb_group = None
        self.buffer = BufferClient(
            self,
            "/tf2_buffer_server",
            timeout_padding=1.0,
            callback_group=self.cb_group,
        )
        self.sub = self.create_subscription(
            msg_type=Empty,
            topic="/test_buffer_client",
            callback=self.buffer_cb,
            qos_profile=1,
        )

    def buffer_cb(self, msg):
        _ = self.buffer.lookup_transform(
            "map",
            "odom",
            rclpy.time.Time(seconds=0, nanoseconds=0),
            timeout=Duration(seconds=1.0),
        )
        self.get_logger().info("Success")

def main(args=None):
    rclpy.init(args=args)
    node = TestNode()
    executor = None
    rclpy.spin(node, executor)

if __name__ == "__main__":
    main()
```

Make sure the buffer server is already running and there is a valid transform between map->odom. Then publish to the topic that calls `BufferClient.lookup_transform`.

```
ros2 topic pub -1 /test_buffer_client std_msgs/msg/Empty
```

The traceback is:
```
Traceback (most recent call last):
  File "/workspace/rover/ros2/install/navigation/lib/navigation/navigation_test", line 33, in <module>
    sys.exit(load_entry_point('navigation', 'console_scripts', 'navigation_test')())
  File "/workspace/rover/ros2/build/navigation/navigation/node_test.py", line 53, in main
    rclpy.spin(node, executor)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/__init__.py", line 191, in spin
    executor.spin_once()
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 711, in spin_once
    raise handler.exception()
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 426, in handler
    await call_coroutine(entity, arg)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 351, in _execute_subscription
    await await_or_execute(sub.callback, msg)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 118, in await_or_execute
    return callback(*args)
  File "/workspace/rover/ros2/build/navigation/navigation/node_test.py", line 33, in buffer_cb
    _ = self.buffer.lookup_transform(
  File "/opt/ros/foxy/lib/python3.8/site-packages/tf2_ros/buffer_client.py", line 87, in lookup_transform
    return self.__process_goal(goal)
  File "/opt/ros/foxy/lib/python3.8/site-packages/tf2_ros/buffer_client.py", line 201, in __process_goal
    raise tf2.TimeoutException("The LookupTransform goal sent to the BufferServer did not come back in the specified time. Something is likely wrong with the server")
tf2.TimeoutException: The LookupTransform goal sent to the BufferServer did not come back in the specified time. Something is likely wrong with the server
```

#### Expected behavior
It shouldn't crash since it works with the ros2 cli. If you use the following it works:
```
ros2 action send_goal /tf2_buffer_server tf2_msgs/action/LookupTransform '{target_frame: map, source_frame: odom}'
```

#### Actual behavior
It timeouts every time.

### Additional notes
I modified https://github.com/ros2/geometry2/blob/ros2/tf2_ros_py/tf2_ros/buffer_client.py#L61 to accept also a callback group that is passed to the `ActionClient`. Then, in the `TestNode` example above I set the `self.cb_group=ReentrantCallbackGroup()` and the executor to be a `MultiThreadedExecutor`. Only that way it works.

I am missing something?

**Comment by charlielito** [comment]
I am also having the same issue in `rclpp`, when using this inside a callback the `BufferClient.lookupTransform` timeouts.
@clalancette  I see there are some tests for this but not for testing it inside a callback function.

**Comment by karl-schulz** [comment]
I have the same problem - I think this feature is actually not ready to be used?

**Comment by clalancette** [comment]
> I am also having the same issue in `rclpp`, when using this inside a callback the `BufferClient.lookupTransform` timeouts.
> @clalancette I see there are some tests for this but not for testing it inside a callback function.

For better or worse, that is by design.  The problem with doing this is that you are blocking the executor, but the executor needs to run in order to get the transform.

The solution here is to make sure to never run blocking functions like `lookupTransform` from within a callback, or you use the MultiThreadedExecutor, or you instantiate the `TransformListener` with `spin_thread = True`.

**Comment by karl-schulz** [comment]
Thanks! That makes sense, however is the usage of a separate thread in the `BufferClient` necessary in that case? We could use event.wait with a timeout instead of starting a new thread to check for a timeout, right?
https://docs.python.org/3/library/threading.html#threading.Event.wait

**Comment by charlielito** [comment]
> > I am also having the same issue in `rclpp`, when using this inside a callback the `BufferClient.lookupTransform` timeouts.
> > @clalancette I see there are some tests for this but not for testing it inside a callback function.
> 
> For better or worse, that is by design. The problem with doing this is that you are blocking the executor, but the executor needs to run in order to get the transform.
> 
> The solution here is to make sure to never run blocking functions like `lookupTransform` from within a callback, or you use the MultiThreadedExecutor, or you instantiate the `TransformListener` with `spin_thread = True`.

`BufferClient` doesn't have any `TransformListener`. Also using `MultiThreadedExecutor` does not work, you have to pass a `ReentrantCallbackGroup` to the client inside the `BufferClient` class -which currently is not exposed- as already mentioned in the issue.

**Comment by padhupradheep** [comment]
Is there any update on the issue? I'm also facing the same issue, but it is with rclcpp!

**Comment by Flova** [comment]
This could be fixed by spinning a separate callback group in a separate thread. Independent execution of callback groups is currently only supported in rclcpp, but this pr aimed at implementing them https://github.com/ros2/rclpy/pull/909.
TF2 also features a not so clean fix. You can pass the TransformListener a newly created node object. This new node is used to gather the transforms in parallel if you also set spin_thread to True.

**Comment by charlielito** [comment]
I think there is a misunderstanding here. The issue described in this thread refers to the [`BufferClient` class](https://github.com/ros2/geometry2/blob/ros2/tf2_ros_py/tf2_ros/buffer_client.py) which has nothing to do with a `TransformListener`. The `BufferClient` is just wrapping a `rclpy.action.client.ActionClient` to call a `tf2_ros buffer_server` using that client.

**Comment by Flova** [comment]
Oh nvm. I missread this.

**Comment by tigelbri** [comment]
I do have the same problem right now. Do I really need to change the BufferClient Interface or is there an other way of handling this issue?

**Comment by bobbleballs** [comment]
Hi all, thanks very much for your input. I ran into this issue and I've found a solution that doesn't require changing the BufferClient interface, though I do think this should be changed. @clalancette is there any progress on this?
A quick and dirty way is to change the Node's default callback group to a ReentrantCallbackGroup() then using a multithreaded excecutor to run the node. This way when you create the BufferClient it will use a ReentrantCallbackGroup by default.
Some example code below:
```
class ExampleActionServer(Node):
      def __init__(self):
          super().__init__('example_action_server')
          # Set the nodes default callback group to ReentrantCallbackGroup()
          self._default_callback_group = ReentrantCallbackGroup()
          self.tf_buffer = BufferClient(self, "/tf_action")
          self.tf_buffer.action_client.wait_for_server(5.0)
  
          self._action_server = ActionServer(
              self,
              ExampleAction,
              'example_action',
              self.execute_callback)

def main():
    rclpy.init()
    excecutor = rclpy.executors.MultiThreadedExecutor()
    
    example_action_server = ExampleActionServer()
    
    excecutor.add_node(example_action_server)
    excecutor.spin()
```
I've found that the buffer client does work from a callback this way.

**Comment by tonynajjar** [comment]
This blog is quite relevant for this issue to better understand it; https://karelics.fi/deadlocks-in-rclpy/

I would propose to the maintainers to put the service client of the BufferClient in a separate callback group, like is done for the [subscribers of the transform listener](https://github.com/pixel-robotics/geometry2/blob/6530c38d5d52fb145940a04e65f7503c03391961/tf2_ros_py/tf2_ros/transform_listener.py#L82)

**Comment by reinzor** [comment]
For people running into this problem:

Setting `spin_thread` to `true` did not fix my problem of doing `transform` lookups within a callback. Adding a `rclpy.executors.MultiThreadedExecutor` did.

**Comment by Flova** [comment]
Also, for people that have timeout/blocking issues in ROS2 in general, the multithreaded executor helps. But keep in mind that the default callback group is mutually exclusive and you need to select a reentrant callback group (or multiple mutually exclusive ones) for the involved callbacks to use multiple threads in the multithreaded executor.

**Comment by zacharyyamaoka** [comment]
I was getting poor performance using a tf_buffer with multithreaded executors, as the high frequency TF data seemed to overwhelm all the other callback groups.

Here is a log where I do a self.node.create_rate(100).sleep() in an action server while I wait for a condition to be true. I would expect the loop time to be consistent 0.01s, but it has trouble keeping up.
```
[INFO] [1734795460.901186591] [bam_BAMGPU.deltax_server]: Recivied Action Request
[INFO] [1734795460.902852478] [bam_BAMGPU.deltax_server]: Executing goal...
[INFO] [1734795460.904370023] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734795460.905848492] [bam_BAMGPU.deltax_server]: Loop time: 0.001
0.2872281323269015 0.0
[INFO] [1734795460.908104775] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734795460.909355380] [bam_BAMGPU.deltax_server]: Loop time: 0.004
0.2872281323269015 0.0
[INFO] [1734795460.913589135] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734795460.920546263] [bam_BAMGPU.deltax_server]: Loop time: 0.005
0.2872281323269015 0.0
[INFO] [1734795460.924742035] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734795460.929696233] [bam_BAMGPU.deltax_server]: Loop time: 0.011
0.2872281323269015 0.0
[INFO] [1734795460.934394203] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734795460.940699708] [bam_BAMGPU.deltax_server]: Loop time: 0.01
0.2872281323269015 0.0
[INFO] [1734795460.944343166] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734795460.944838221] [bam_BAMGPU.deltax_server]: Loop time: 0.01
0.2870122760440745 0.0
[INFO] [1734795461.850687009] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734795462.905678193] [bam_BAMGPU.deltax_server]: Loop time: 0.906
7.141428428546883e-05 0.0
```


Removing TF from the script fixes the issue, and the loop time is a consistent 0.01s. Here is the problematic code:
  
```python
self.tf_buffer = Buffer()
self.tf_listener = TransformListener(self.tf_buffer, self, spin_thread=False)
```


After searching online I found this article: https://robotics.stackexchange.com/questions/99416/transformlistener-x10-higher-cpu-load-in-rclpy-than-rclpp , which lead me to here! Instead of using a TransformListenter, I am now using the BufferClient

```python
# self.tf_buffer = Buffer()
# self.tf_listener = TransformListener(self.tf_buffer, self, spin_thread=False) 
self.tf_buffer_client = BufferClient(self, f"{self.get_namespace()}/tf2_buffer_server", check_frequency=100)
```

After launching the BufferServer

```python
    tf_buffer_server = Node(
    package="tf2_ros",
    executable="buffer_server",
    output="both",
    emulate_tty=True
    )
```

As others described, I can query the server from ros cli

```
ros2 action send_goal /tf2_buffer_server tf2_msgs/action/LookupTransform '{target_frame: base_link, source_frame: eef_link}'
```

I was also able to connect to the server

```python
self.tf_buffer_client.action_client.wait_for_server(5)
```

However, I could not get a transform! It would just time out. Problematic code:

```python
self.tf_buffer_client.lookup_transform(self.planning_frame, self.eef_frame,rclpy.time.Time())
```

I have edited the __process_goal() function in buffer_client.py to use a rate.sleep() instead. I also just call the lookup_transform  within another action callback. If I call lookup_transform during the node __init__() it will block as it's sleeping on the main thread.

```python
def __process_goal(self, goal: LookupTransformGoal) -> TransformStamped:
# TODO(sloretz) why is this an action client? Service seems more appropriate.
if not self.action_client.server_is_ready():
    raise tf2.TimeoutException("The BufferServer is not ready.")

send_goal_future = self.action_client.send_goal_async(goal)

clock = Clock()
start_time = clock.now()
timeout = Duration.from_msg(goal.timeout)
timeout_padding = self.timeout_padding

while not send_goal_future.done():
    if clock.now() > start_time + timeout + timeout_padding:
        break
    self.check_if_done_rate.sleep()

# This shouldn't happen, but could in rare cases where the server hangs
if not send_goal_future.done():
    raise tf2.TimeoutException("The LookupTransform goal sent to the BufferServer did not come back in the specified time. Something is likely wrong with the server.")

# Raises if future was given an exception
goal_handle = send_goal_future.result()

if not goal_handle.accepted:
    raise tf2.TimeoutException("The LookupTransform goal sent to the BufferServer did not come back with accepted status. Something is likely wrong with the server.")

response = self.action_client._get_result(goal_handle)

return self.__process_result(response.result)
```

How I use it

```python
class ActionServer(Node):
   
    def __init__(self):
        super().__init__('my_action_server')

        self.action_cb_group = ReentrantCallbackGroup()
        self.action_server = ActionServer(self, RobotAPI, 'robot_api/request', self.action_callback, callback_group=self.action_cb_group)
        
        self.result = RobotAPI.Result()
        self.waiting_rate = self.create_rate(100)

        self.tf_buffer_client = BufferClient(self, f"{self.get_namespace()}/tf2_buffer_server", check_frequency=100)
        
        self.planning_frame = 'base_link'
        self.eef_frame = 'xyz_link'
        self.eef_target_frame = 'eef_target'

        if not self.tf_buffer_client.action_client.wait_for_server(5):
            self.get_logger().error(f"Could not connect to TF buffer server")

         #  With my changes, lookup_transform doesn't work here, as the rate.sleep() inside the function blocks
         # t_eef = self.tf_buffer_client.lookup_transform(self.planning_frame, self.eef_frame,rclpy.time.Time())

    def action_callback(self, goal_handle):

        goal_handle.succeed()

        pose = goal_handle.request.waypoints[0]
        t_eef_target = pose_to_transform_stamped(pose, self.planning_frame, self.eef_target_frame, self.get_clock().now().to_msg())
        t_eef_target = t_eef_target.transform
        
        while True:
            self.waiting_rate.sleep()
            
           # lookup_transform works within callback, as main thread can continue spining and rate.sleep() doesn't block
            t_eef = self.tf_buffer_client.lookup_transform(self.planning_frame, self.eef_frame,rclpy.time.Time())
            t_eef = t_eef.transform

            pos_diff, rot_diff = pose_difference(t_eef.translation, t_eef.rotation, t_eef_target.translation, t_eef_target.rotation)

            if pos_diff < 0.005:
                break

        return self.result 
       
def main(args=None):
    rclpy.init(args=args)

    node = ActionServer()    
    executor = MultiThreadedExecutor()
    executor.add_node(node)
    executor.spin()

    rclpy.shutdown()
    exit(0)

if __name__ == "__main__":
    main()

```

This works really well now!

```
[INFO] [1734800979.210071685] [bam_BAMGPU.deltax_server]: Recivied Action Request
[INFO] [1734800979.210310400] [bam_BAMGPU.deltax_server]: Executing goal...
[INFO] [1734800979.210937747] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.211149671] [bam_BAMGPU.deltax_server]: Loop time: 0.0
0.2872281323269015 0.0
[INFO] [1734800979.217518140] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.217728000] [bam_BAMGPU.deltax_server]: Loop time: 0.007
0.2872281323269015 0.0
[INFO] [1734800979.227472890] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.227675847] [bam_BAMGPU.deltax_server]: Loop time: 0.01
0.28720027994415326 0.0
[INFO] [1734800979.237478537] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.237683197] [bam_BAMGPU.deltax_server]: Loop time: 0.01
0.287127167297001 0.0
[INFO] [1734800979.247529400] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.247743919] [bam_BAMGPU.deltax_server]: Loop time: 0.01
0.2870122760440745 0.0
[INFO] [1734800979.257471245] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.257666678] [bam_BAMGPU.deltax_server]: Loop time: 0.01
0.28683993916468464 0.0
[INFO] [1734800979.267574929] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.267773438] [bam_BAMGPU.deltax_server]: Loop time: 0.01
0.28659623043578225 0.0
[INFO] [1734800979.277363792] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.277557061] [bam_BAMGPU.deltax_server]: Loop time: 0.01
0.2863368547707403 0.0
[INFO] [1734800979.287456435] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.287652739] [bam_BAMGPU.deltax_server]: Loop time: 0.01
0.28602177417112845 0.0
[INFO] [1734800979.297528579] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.297724633] [bam_BAMGPU.deltax_server]: Loop time: 0.01
0.28561965478587076 0.0
[INFO] [1734800979.307398116] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.307600452] [bam_BAMGPU.deltax_server]: Loop time: 0.01
0.2852175354006131 0.0
[INFO] [1734800979.317443859] [bam_BAMGPU.deltax_server]: Waiting. . .
[INFO] [1734800979.317651766] [bam_BAMGPU.deltax_server]: Loop time: 0.01
```

A drawback of this solution is that it doesn't work in all cases out of the box. (SingleThreadedExecutors, inside main callback). A benefit is that it's much simpler and understandable. It's just treating it as a normal action client basically, no crazy threading tricks.

**Comment by Flova** [comment]
We now use this hack and it works also really well:
https://github.com/bit-bots/bitbots_tf_buffer

It essentially wraps a rclcpp Node, TF Buffer and Listener in a wrapper that matches the Python ft2.BufferInterface. It is significantly more performant, as all communication is done in cpp and the transform calls are performed directly on the cpp node via shred memory. The only downside is the additional node. 

Additionally, I started porting the events executor to native Python rclpy and got a 5x increased throughput with a quarter of the CPU utilization. But this will take a while to reach production readiness.

**Comment by mbpeterson70** [comment]
This tip from @reinzor worked for me:

> Setting `spin_thread` to `true` did not fix my problem of doing `transform` lookups within a callback. Adding a `rclpy.executors.MultiThreadedExecutor` did.

To add a small detail, for me it was just switching this line in `main` from:

```python
rclpy.spin(node)
```

to

```python
from rclpy.executors import MultiThreadedExecutor

...

executor = MultiThreadedExecutor()
executor.add_node(node)
executor.spin()
```

**Comment by Flova** [comment]
You also need to provide an appropriate amount of threads, otherwise it still deadlocks.

**Comment by Flova** [comment]
Imo a proper async wait for transforms with a timeout that can be awaited would be the way to go. The calling parent function would need to be async too, but rclpy does support async callbacks. This would allow the executor to spin freely during the wait period allowing it to process incoming data eliminateing the deadlock. 

As stated earlier https://github.com/bit-bots/bitbots_tf_buffer is a drop in replacement that also solves this problem, while being also significantly faster.

**Comment by charlielito** [comment]
> Imo a proper async wait for transforms with a timeout that can be awaited would be the way to go. The calling parent function would need to be async too, but rclpy does support async callbacks. This would allow the executor to spin freely during the wait period allowing it to process incoming data eliminateing the deadlock.
> 
> As stated earlier https://github.com/bit-bots/bitbots_tf_buffer is a drop in replacement that also solves this problem, while being also significantly faster.

I agree. A proper AsyncBufferClient should be available to the users. I ported the implementation to use the async api as follows:

```python
#! /usr/bin/python

import tf2_py as tf2
import tf2_ros
import rclpy
import rclpy.task

from rclpy.action.client import ActionClient
from rclpy.duration import Duration
from rclpy.node import Node
from tf2_msgs.action import LookupTransform

async def future_with_timeout(
    node: Node, future: rclpy.task.Future, timeout_sec: float
):
    """!
    function to await a future with a given timeout
    :param node: The ROS2 node.
    :param future: The future to await.
    :param timeout_sec: The timeout.
    :return: The future's result.
    """
    first_done_future = rclpy.task.Future()

    def handler(arg=None):
        first_done_future.set_result(None)

    timer = node.create_timer(timeout_sec, handler)
    future.add_done_callback(handler)

    await first_done_future

    if not future.done():
        raise TimeoutError(f"Future timed out after {timeout_sec} seconds")

    timer.cancel()
    timer.destroy()

    return future.result()


class AsyncBufferClient(tf2_ros.BufferInterface):
    """
    Async action client-based implementation of BufferInterface.
    """

    def __init__(
        self,
        node,
        ns,
        timeout_padding=Duration(seconds=2.0),
        callback_group=None,
    ):
        """
        .. function:: __init__(ns, timeout_padding = rospy.Duration.from_sec(2.0))

            Constructor.

            :param node: The ROS2 node.
            :param ns: The namespace in which to look for a BufferServer.
            :param timeout_padding: A constant timeout to add to blocking calls.
            :param callback_group: The callback group to use for the action client.
        """
        tf2_ros.BufferInterface.__init__(self)
        self.node = node
        self.action_client = ActionClient(
            node, LookupTransform, action_name=ns, callback_group=callback_group
        )
        # Ensure timeout_padding is a Duration object
        if isinstance(timeout_padding, (int, float)):
            self.timeout_padding = Duration(seconds=float(timeout_padding))
        else:
            self.timeout_padding = timeout_padding

    # lookup, simple api
    async def lookup_transform(self, target_frame, source_frame, time, timeout=Duration()):
        """
        Get the transform from the source frame to the target frame.

        :param target_frame: Name of the frame to transform into.
        :param source_frame: Name of the input frame.
        :param time: The time at which to get the transform. (0 will get the latest)
        :param timeout: (Optional) Time to wait for the target frame to become available.
        :return: The transform between the frames.
        :rtype: :class:`geometry_msgs.msg.TransformStamped`
        """
        goal = LookupTransform.Goal()
        goal.target_frame = target_frame
        goal.source_frame = source_frame
        goal.source_time = time.to_msg()
        goal.timeout = timeout.to_msg()
        goal.advanced = False

        return await self.__process_goal(goal, timeout)

    # lookup, advanced api
    async def lookup_transform_full(
        self,
        target_frame,
        target_time,
        source_frame,
        source_time,
        fixed_frame,
        timeout=Duration(),
    ):
        """
        Get the transform from the source frame to the target frame using the advanced API.

        :param target_frame: Name of the frame to transform into.
        :param target_time: The time to transform to. (0 will get the latest)
        :param source_frame: Name of the input frame.
        :param source_time: The time at which source_frame will be evaluated. (0 will get the latest)
        :param fixed_frame: Name of the frame to consider constant in time.
        :param timeout: (Optional) Time to wait for the target frame to become available.
        :return: The transform between the frames.
        :rtype: :class:`geometry_msgs.msg.TransformStamped`
        """
        goal = LookupTransform.Goal()
        goal.target_frame = target_frame
        goal.source_frame = source_frame
        goal.source_time = source_time.to_msg()
        goal.timeout = timeout.to_msg()
        goal.target_time = target_time.to_msg()
        goal.fixed_frame = fixed_frame
        goal.advanced = True

        return await self.__process_goal(goal, timeout)

    # can, simple api
    async def can_transform(self, target_frame, source_frame, time, timeout=Duration()):
        """
        Check if a transform from the source frame to the target frame is possible.

        :param target_frame: Name of the frame to transform into.
        :param source_frame: Name of the input frame.
        :param time: The time at which to get the transform. (0 will get the latest)
        :param timeout: (Optional) Time to wait for the target frame to become available.
        :param return_debug_type: (Optional) If true, return a tuple representing debug information.
        :return: True if the transform is possible, false otherwise.
        :rtype: bool
        """
        try:
            await self.lookup_transform(target_frame, source_frame, time, timeout)
            return True
        except tf2.TransformException:
            return False

    # can, advanced api
    async def can_transform_full(
        self,
        target_frame,
        target_time,
        source_frame,
        source_time,
        fixed_frame,
        timeout=Duration(),
    ):
        """
        Check if a transform from the source frame to the target frame is possible (advanced API).

        Must be implemented by a subclass of BufferInterface.

        :param target_frame: Name of the frame to transform into.
        :param target_time: The time to transform to. (0 will get the latest)
        :param source_frame: Name of the input frame.
        :param source_time: The time at which source_frame will be evaluated. (0 will get the latest)
        :param fixed_frame: Name of the frame to consider constant in time.
        :param timeout: (Optional) Time to wait for the target frame to become available.
        :param return_debug_type: (Optional) If true, return a tuple representing debug information.
        :return: True if the transform is possible, false otherwise.
        :rtype: bool
        """
        try:
            await self.lookup_transform_full(
                target_frame,
                target_time,
                source_frame,
                source_time,
                fixed_frame,
                timeout,
            )
            return True
        except tf2.TransformException:
            return False

    async def __process_goal(self, goal, timeout=Duration()):
        # Check if action server is ready
        if not self.action_client.server_is_ready():
            raise tf2.TimeoutException("The BufferServer is not ready")

        # Send the goal
        send_goal_future = self.action_client.send_goal_async(goal)
        
        # Calculate total timeout using goal timeout plus padding
        goal_timeout_secs = Duration.from_msg(goal.timeout).nanoseconds / 1e9
        
        # Ensure timeout_padding is handled correctly
        if isinstance(self.timeout_padding, Duration):
            padding_secs = self.timeout_padding.nanoseconds / 1e9
        else:
            padding_secs = float(self.timeout_padding)
            
        total_timeout_secs = goal_timeout_secs + padding_secs
        
        try:
            # Wait for send_goal response with timeout
            goal_handle = await future_with_timeout(
                self.node, send_goal_future, total_timeout_secs
            )
            
            if not goal_handle.accepted:
                raise tf2.TimeoutException(
                    "The LookupTransform goal sent to the BufferServer was not accepted. Something is likely wrong with the server."
                )
                
            # Get the result
            get_result_future = goal_handle.get_result_async()
            
            # Wait for result with timeout
            response = await future_with_timeout(
                self.node, get_result_future, total_timeout_secs
            )
            return self.__process_result(response.result)
            
        except TimeoutError:
            raise tf2.TimeoutException(
                "The LookupTransform request to the BufferServer timed out. Something is likely wrong with the server."
            )

    def __process_result(self, result):
        if result is None or result.error is None:
            raise tf2.TransformException(
                "The BufferServer returned None for result or result.error! Something is likely wrong with the server."
            )
        if result.error.error != result.error.NO_ERROR:
            if result.error.error == result.error.LOOKUP_ERROR:
                raise tf2.LookupException(result.error.error_string)
            if result.error.error == result.error.CONNECTIVITY_ERROR:
                raise tf2.ConnectivityException(result.error.error_string)
            if result.error.error == result.error.EXTRAPOLATION_ERROR:
                raise tf2.ExtrapolationException(result.error.error_string)
            if result.error.error == result.error.INVALID_ARGUMENT_ERROR:
                raise tf2.InvalidArgumentException(result.error.error_string)
            if result.error.error == result.error.TIMEOUT_ERROR:
                raise tf2.TimeoutException(result.error.error_string)

            raise tf2.TransformException(result.error.error_string)

        return result.transform 
```

Then it can be easily used with a single-thread node like this:

```python
#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from async_buffer_client import AsyncBufferClient
from rclpy.duration import Duration
from std_msgs.msg import Empty
from rclpy.callback_groups import ReentrantCallbackGroup

class TestNode(Node):
    def __init__(
        self,
    ):
        super().__init__("test_node")
        self.buffer = AsyncBufferClient(
            self,
            "/tf2_buffer_server",
        )
        self.sub = self.create_subscription(
            msg_type=Empty,
            topic="/test_buffer_client",
            callback=self.buffer_cb,
            qos_profile=1,
            callback_group=ReentrantCallbackGroup(),
        )

    async def buffer_cb(self, msg):
        result = await self.buffer.lookup_transform(
            "map",
            "odom",
            rclpy.time.Time(seconds=0, nanoseconds=0),
            timeout=Duration(seconds=0.1),
        )
        self.get_logger().info(f"Success: {result}")

def main(args=None):
    rclpy.init(args=args)
    node = TestNode()
    rclpy.spin(node)

if __name__ == "__main__":
    main()
```

**Comment by charlielito** [comment]
> We now use this hack and it works also really well: https://github.com/bit-bots/bitbots_tf_buffer
> 
> It essentially wraps a rclcpp Node, TF Buffer and Listener in a wrapper that matches the Python ft2.BufferInterface. It is significantly more performant, as all communication is done in cpp and the transform calls are performed directly on the cpp node via shred memory. The only downside is the additional node.
> 
> Additionally, I started porting the events executor to native Python rclpy and got a 5x increased throughput with a quarter of the CPU utilization. But this will take a while to reach production readiness.

@Flova I am curious if you finished the port of the events executor to native python and where can we find it?

**Comment by Flova** [comment]
> I agree. A proper AsyncBufferClient should be available to the users. I ported the implementation to use the async api as follows:

Look very cool. I would be glad if we could get something like this upstream with a PR. I also think that the "normal" non service client buffer could very much benefit from this.  


> [@Flova](https://github.com/Flova) I am curious if you finished the port of the events executor to native python and where can we find it?

I wan't the only one working on an implementation of the events executor for Python and somebody finished a more polished version first. It has been added to rolling in https://github.com/ros2/rclpy/pull/1391 and I have backported this implementation to jazzy in https://github.com/ros2/rclpy/pull/1435.
