### ISSUE TITLE
:farmer: Flaky `test_static_publisher.launch.py` in tf2

### ISSUE THREAD

**Issue by Crola1702** [ros2/geometry2#583]
## Bug report

**Required Info:**

- Operating System:
  - Windows, Ubuntu 20.04
- Installation type:
  - Source
- Version or commit hash:
  - Foxy, Rolling

#### Steps to reproduce issue

1. Run a build in one of the following jobs:  nightly_win_rel, nightly_win_rep, Fci_nightly_connext, Rci_nightly_connext
2. See test_static_publisher.launch.py fail if lucky

#### Expected behavior

test_static_publisher.launch.py should pass

#### Actual behavior

test_static_publisher.launch.py fails

### Windows release | Test regression | Keeping track :eyes:  

Reference build: https://ci.ros2.org/view/nightly/job/nightly_win_rel/2583/

Failing test: [projectroot.test_static_publisher.launch.py](https://ci.ros2.org/view/nightly/job/nightly_win_rel/2583/testReport/junit/(root)/projectroot/test_static_publisher_launch_py/)

Log output:
<details>

```
...
[test_static_publisher.EXE-3] Warning: Invalid frame ID "c" passed to canTransform argument source_frame - frame does not exist
[test_static_publisher.EXE-3]          at line 93 in C:\ci\ws\src\ros2\geometry2\tf2\src\buffer_core.cpp
[test_static_publisher.EXE-3] Warning: Invalid frame ID "c" passed to canTransform argument source_frame - frame does not exist
[test_static_publisher.EXE-3]          at line 93 in C:\ci\ws\src\ros2\geometry2\tf2\src\buffer_core.cpp
[test_static_publisher.EXE-3] Warning: Invalid frame ID "c" passed to canTransform argument source_frame - frame does not exist
[test_static_publisher.EXE-3]          at line 93 in C:\ci\ws\src\ros2\geometry2\tf2\src\buffer_core.cpp
[test_static_publisher.EXE-3] C:\ci\ws\src\ros2\geometry2\test_tf2\test\test_static_publisher.cpp(103): error: Failed
[ERROR] [test_static_publisher.EXE-3]: process has died [pid 28600, exit code 3, cmd 'C:\ci\ws\install\lib\test_tf2\test_static_publisher.EXE --ros-args'].
[WARNING] [python.exe-4]: 'SIGINT' sent to process[python.exe-4] not supported on Windows, escalating to 'SIGTERM'
...
[ERROR] [static_transform_publisher.EXE-2]: process has died [pid 8664, exit code 1, cmd 'C:\ci\ws\install\lib\tf2_ros\static_transform_publisher.EXE --x 0 --y 1 --z 0 --qx 0 --qy 0 --qz 0 --qw 1 --frame-id b --child-frame-id c --ros-args'].
[ERROR] [static_transform_publisher.EXE-1]: process has died [pid 17524, exit code 1, cmd 'C:\ci\ws\install\lib\tf2_ros\static_transform_publisher.EXE --x 1 --y 0 --z 0 --qx 0 --qy 0 --qz 0 --qw 1 --frame-id a --child-frame-id b --ros-args'].
ok
...
FAIL: test_exit_code (test_tf2.BufferClientTestAfterShutdown)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ci\ws\src\ros2\geometry2\test_tf2\test\static_publisher.launch.py", line 54, in test_exit_code
    launch_testing.asserts.assertExitCodes(proc_info)
  File "C:\ci\ws\install\Lib\site-packages\launch_testing\asserts\assert_exit_codes.py", line 62, in assertExitCodes
    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(
AssertionError: Proc test_static_publisher.EXE-3 exited with code 3

```

</details> 

---

Last 11 times it happened:
| Job name | Build number | Date |
| -- | -- | -- |
|nightly_win_rel|2583|2023-02-06 |
|Fci__nightly-connext_ubuntu_focal_amd64|489|2023-02-05 |
|Rci__nightly-connext_ubuntu_jammy_amd64|340|2023-02-03 |
|Fci__nightly-connext_ubuntu_focal_amd64|488|2023-02-02 |
|Fci__nightly-connext_ubuntu_focal_amd64|486|2023-02-01 |
|Fci__nightly-connext_ubuntu_focal_amd64|485|2023-01-29 |
|Fci__nightly-connext_ubuntu_focal_amd64|484|2023-01-26 |
|nightly_win_rep|2879|2023-01-24 |
|Fci__nightly-connext_ubuntu_focal_amd64|483|2023-01-23 |
|Fci__nightly-connext_ubuntu_focal_amd64|482|2023-01-20 |
|nightly_win_rep|2872|2023-01-17 |

Log output for Foxy and Rolling is almost the same, so it's not a Windows error.

As it fails on Windows Repeated with very low ratio (twice per month) this is a Flaky issue

**Comment by Crola1702** [comment]
This regression hasn't happened since 2024-02-21. I'll close it for now until we see it again
